# Generated by Django 5.0.2 on 2024-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("litter", "0002_alter_litterinstance_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="litterinstance",
            name="approved",
            field=models.IntegerField(default=0),
        ),
    ]
