# Generated by Django 5.0.2 on 2024-02-20 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LitterInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(decimal_places=7, default=0, max_digits=10),
                ),
                (
                    "lon",
                    models.DecimalField(decimal_places=7, default=0, max_digits=10),
                ),
                ("img", models.ImageField(blank=True, null=True, upload_to="")),
                ("datetime", models.DateTimeField(verbose_name="Date submitted")),
                ("approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
