# Generated by Django 5.0.1 on 2024-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litterinstance',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/litter/'),
        ),
    ]
