# Generated by Django 5.0.2 on 2024-02-29 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0003_alter_litterinstance_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='litterinstance',
            name='approved',
            field=models.IntegerField(default=0, verbose_name='Approval status'),
        ),
        migrations.AlterField(
            model_name='litterinstance',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/litter/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='litterinstance',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='litterinstance',
            name='lon',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='litterinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
