# Generated by Django 5.0.2 on 2024-03-19 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('points_worth', models.IntegerField(default=0)),
                ('router_ip', models.CharField(max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
                ('attendees', models.TextField(blank=True)),
            ],
        ),
    ]
