# Generated by Django 5.0.1 on 2024-03-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='points_worth',
        ),
    ]
