# Generated by Django 5.0.1 on 2024-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='endorsements',
            field=models.IntegerField(default=1),
        ),
    ]
