# Generated by Django 5.0.1 on 2024-03-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_suggestion_endorsements'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='endorsements',
            field=models.IntegerField(default=1),
        ),
    ]
