# Generated by Django 5.0.2 on 2024-02-29 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_suggestions_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='linked_announced',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='linked_announced_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.annoucement'),
        ),
        migrations.AlterField(
            model_name='annoucement',
            name='post_text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='post_text',
            field=models.CharField(max_length=400),
        ),
    ]
