# Generated by Django 5.0.2 on 2024-02-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_suggestion_linked_announced_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='linked_announced_id',
            new_name='linked_announced',
        ),
    ]
