# Generated by Django 5.0.2 on 2024-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('participants', models.TextField(blank=True)),
                ('num_participants', models.IntegerField(default=0)),
                ('points_accumulated', models.IntegerField(default=0)),
            ],
        ),
    ]
