# Generated by Django 5.0.1 on 2024-03-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks_till_next',
            field=models.IntegerField(default=1),
        ),
    ]
