from typing import Any
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse, HttpResponseForbidden
from .models import PlaceOfInterest
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from .forms import PlaceOfInterestForm
from json import dumps

# Create your views here.

def submit(request: HttpRequest) -> HttpResponse | HttpResponseRedirect | HttpResponseForbidden:
    '''
    Endpoint for users to report an instance of litter on campus

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django

    Returns
    -------
    HttpResponse or HttpResponseRedirect
        Containing the report.html webpage.
        If HttpResponseRedirect it means that a POST request was received and some litter was reported
    '''
    if not request.user.is_staff:
        HttpResponseForbidden()

    submitted = False
    id = -1
    if request.method == "POST":
        # Populate the form with the POST and FILES data
        form = PlaceOfInterestForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            poi = PlaceOfInterest.objects.get(pk=obj.id)
            return HttpResponseRedirect(f'/poi/submit?submitted=True&id={poi.id}')
    else:  # Is a GET request
        # Create a blank form
        form = PlaceOfInterestForm
        # Check if the GET request is a result of the redirect after a post
        if 'submitted' in request.GET and 'id' in request.GET:
            submitted = True
            id = request.GET['id']

    return render(request, 'poi/submit.html', {'form': form, 
                                                  'submitted': submitted, 
                                                  'id': id,
                                                  'is_staff': request.user.is_staff})