# Generated by Django 5.0.2 on 2024-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaceOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.TextField(default="", verbose_name="Description")),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=7,
                        default=0,
                        max_digits=10,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=7,
                        default=0,
                        max_digits=10,
                        verbose_name="Longitude",
                    ),
                ),
            ],
        ),
    ]
