# Generated by Django 5.0.2 on 2024-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeofinterest",
            name="title",
            field=models.CharField(default="", max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="placeofinterest",
            name="desc",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="placeofinterest",
            name="lat",
            field=models.DecimalField(
                decimal_places=15, max_digits=18, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="placeofinterest",
            name="lon",
            field=models.DecimalField(
                decimal_places=15, max_digits=18, verbose_name="Longitude"
            ),
        ),
    ]
