# Generated by Django 5.0.2 on 2024-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poi", "0003_alter_placeofinterest_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeofinterest",
            name="lat",
            field=models.DecimalField(
                decimal_places=16, max_digits=19, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="placeofinterest",
            name="lon",
            field=models.DecimalField(
                decimal_places=16, max_digits=19, verbose_name="Longitude"
            ),
        ),
    ]
